### ISSUE TITLE
合言葉でマッチングできるようにする

### ISSUE THREAD

**Issue by YoshiTa0527** [YoshiTa0527/ps20a-network#15]
細かな仕様は書き足していってください。

**Comment by kojima0725** [comment]
ロビーには文字入力を受け付けるインプットフィールドがあり、合言葉が合致した人(フレンド)とプレイできるようにする。
最初に合言葉を入力した時(入力された名前のルームが存在しなかった場合)ルームが作成され、ゲームシーンに移動する。
次に合言葉を入力した人がそのルームに入れるようにする。
２人入った時点でその部屋は締め切られ、３人め以降が同じ合言葉を入力した場合はエラーメッセージを出して跳ね返す

**Comment by kojima0725** [comment]
作業は「lobbysystem」ブランチで行う

**Comment by kojima0725** [comment]
機能が完成したのでプルリクエストを送った

**Comment by kojima0725** [comment]
ロビーの機能は完成し、デベロップブランチにマージされました
