### ISSUE TITLE
敵の種類を増やす

### ISSUE THREAD

**Issue by YoshiTa0527** [YoshiTa0527/ps20a-network#61]

**Comment by YoshiTa0527** [comment]
今ある素材。
敵：直進する敵・カーブアップする敵・カーブダウンする敵・八の字で動く敵・二段階で動く敵。
弾：直進する弾・自機狙い弾・2Way。

**Comment by YoshiTa0527** [comment]
①直進する敵＝直進弾
②直進する敵＝自機狙い。
③カーブアップ＝直進。
④カーブダウン＝自機狙い。
⑤八の字＝2Way。
⑥二段階＝2way。

**Comment by HiraEi** [comment]
命名規則
動き+弾の種類

**Comment by HiraEi** [comment]
敵ができたら
Assets/Resources/Enemy
に入れる

**Comment by YoshiTa0527** [comment]
完成
